### ISSUE TITLE
你好.想问问关于登陆账号的

### ISSUE THREAD

**Issue by lhzlhzvip** [kbdancer/TPLINKKEY#1]
大大你好.
虽然这个不是关于你写的码,但是我现在想写一个码
用python的urllib之类的登陆tplink的管理端.然后查看在线设备的mac地址.
但是我看了一下那个登录端是没post之类代码,而且没用户名.

在百度youtube都看了下,都是挺老的东西了,估计都没人做这玩意.
请问下你有什么建议吗?

**Comment by kbdancer** [comment]
这个我想应该很简单，你能截个图给我吗，就是你想登录的那个界面是什么样子的。一般路由器登录都是401认证，用urllib实现比较复杂，建议用requests，非常简单

发自 网易邮箱大师
在2016年02月24日 03:57，lhzlhzvip 写道:

大大你好.
虽然这个不是关于你写的码,但是我现在想写一个码
用python的urllib之类的登陆tplink的管理端.然后查看在线设备的mac地址.
但是我看了一下那个登录端是没post之类代码,而且没用户名.

在百度youtube都看了下,都是挺老的东西了,估计都没人做这玩意.
请问下你有什么建议吗?

**Comment by lhzlhzvip** [comment]
我用urllib读了下(code.txt)弄了好多次都po不齐... 另外我在这也看到有人最近写了个php的.但是要用curl登陆.(关键是不太会php)
https://github.com/xuhuazai/tplink-restart

(我现在是迅捷的路由器(fast.jpg),但是以后做的东西是用在tplink上的,但其实这俩货都是一个妈的)

[code.txt](https://github.com/kbdancer/TPLINKKEY/files/144280/code.txt)
![fast](https://cloud.githubusercontent.com/assets/17210147/13281583/f18d1af6-dae4-11e5-8532-0085a5463285.jpg)

**Comment by kbdancer** [comment]
你用php写还是Python呢？

**Comment by lhzlhzvip** [comment]
我是想用python写呢.

**Comment by lhzlhzvip** [comment]
另外想问问您,一个网页直接用htaccess来限制var/www的文件夹会不会很容易被破?我看见通常破开这样的认证都是上传.htaccess的文件的.但是我这样挡在家门,估计是连上传的机会都没有吧?

**Comment by kbdancer** [comment]
问题1：我这里暂时只有小米路由器，登录界面和你那个类似，我晚上写个给你参考下，你也可以参考下我另外一个项目，是401 认证的 https://github.com/kbdancer/hkdvr_login
问题2：对于htaccess的安全性我并没有深入研究，不过我看到很多主机上的控制面板上对于目录的限制确实是使用的htaccess，我推测服务端首先读取htaccess文件，然后根据文件的配置规则把http请求转发到对应的模块处理，这样应该算是比较安全的做法。

**Comment by lhzlhzvip** [comment]
感谢!

**Comment by kbdancer** [comment]
我写了个登录小米路由器的，你可以参考下 链接 http://www.92ez.com/index.php?action=show&id=23373

**Comment by lhzlhzvip** [comment]
卧槽,太棒了.还有教程!!
