### ISSUE TITLE
自定义IP字典列表

### ISSUE THREAD

**Issue by zhumingyu** [kbdancer/TPLINKKEY#3]
Hey,guy!
   目前的命令是加IP范围，如果我用包含所有我想扫描的IP列表，那么具体代码如何修改？thks
例：
命令: python telnetkey.py 200 iplistDictionary
iplistDictionary内容形式如下：
114.224.0.1
114.224.0.2
114.224.0.3
114.224.0.4
114.224.0.5
114.224.0.6
114.224.0.7
114.224.0.8
114.224.0.9
114.224.0.10
114.224.0.11
114.224.0.12
114.224.0.13
114.224.0.14
114.224.0.15
114.224.0.16
114.224.0.17
114.224.0.18
114.224.0.19
114.224.0.20
114.224.0.21
114.224.0.22
114.224.0.23
114.224.0.24
114.224.0.25
....................

**Comment by kbdancer** [comment]
看起来似乎是想加上文件读取的功能，是这个意思？

**Comment by zhumingyu** [comment]
是的，朋友！另外加上将终端命令行下输出的日志信息存入指定路径下文件中.thks for advance.
