### ISSUE TITLE
用树莓派跑多线程报错

### ISSUE THREAD

**Issue by tmcyfy** [kbdancer/TPLINKKEY#4]
==========================================
 Scan TPLINK(MERCURY) wifi key by telnet
           Author 92ez.com
==========================================

[*] Total 4607 IP...

================ Running =================
Traceback (most recent call last):
  File "./scan.py", line 151, in <module>
    bThread(iplist)
  File "./scan.py", line 47, in bThread
    t.join()
  File "/usr/lib/python2.7/threading.py", line 929, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started

**Comment by kbdancer** [comment]
你线程开了多少？

**Comment by tmcyfy** [comment]
3000

**Comment by kbdancer** [comment]
树莓派性能可能不足以开3000线程，建议开800以下试试看
