### ISSUE TITLE
脚本现在是不是不可以用了  

### ISSUE THREAD

**Issue by chiseller** [kbdancer/TPLINKKEY#5]
跑了一上午，没反应
![image](https://user-images.githubusercontent.com/25734166/27776956-72fbb660-5fe1-11e7-9760-ddd7ac14f2d5.png)

**Comment by kbdancer** [comment]
这个脚本好久没维护了，可能是扫描的ip段比较少或者你用的宽带不允许扫描导致的

2017年7月3日 11:19，"chiseller" <notifications@github.com>写道：

**Comment by chiseller** [comment]
谢谢

2017-07-04 18:48 GMT+08:00 一只猿 <notifications@github.com>:

**Comment by lvwuyunlifan** [comment]
现在服务器还开着吗，获得key的网址一直连不上去。。。

**Comment by kbdancer** [comment]
这个需要自行搭建服务端环境，我这里是没有提供服务端的

2017年7月27日 09:33，"Mr.Lv@Li" <notifications@github.com>写道：

**Comment by lvwuyunlifan** [comment]
我是个新手，不知道怎么搭建服务端环境惹，下载的源文件中没有manage.py，我就不知道怎么打开服务器了，看了README文件，也不知道怎么使用，有点不知所措

**Comment by lvwuyunlifan** [comment]
求解，谢谢啦

**Comment by iamsunsir** [comment]
扫描的ip段比较少可以解决，如果是宽带不允许扫描所导致该怎么办呢？
