### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by factoid233** [kbdancer/TPLINKKEY#6]
Traceback (most recent call last):
  File "scan.py", line 172, in <mod
    SET_THREAD = int(sys.argv[1])
IndexError: list index out of range

**Comment by kbdancer** [comment]
第一个参数是线程数，你设置了吗

**Comment by iamsunsir** [comment]
为什么我跑了好多ip段都没有扫出来一个？o(╥﹏╥)o
作者给点意见呗。

**Comment by kbdancer** [comment]
现在很多地方都已经没有adsl了，TPLINK漏洞基本上都是在adsl网络上才会有并且需要路由器直接能够得带公网ip
